# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81591bff505d5e44c540f7f1721cf7399e46f95b21f5ca971253741ceba70b2e0c93d52d9135e2b53f90fbab227f52f52e75dbb444aca3740a82c9d9f3666737

test:
  secret_key_base: 5cf0f0850c62e893676ef979374549b3df7df4e25c95f8e563a50fcdb6fa83c392a58bf2443cf45b1f96026cf776b6a5942c07cfbeddf97a6072b15d8bb81f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
